"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ---------------------------------------------------------------------------
# Song generation strategy (Exercise 4 — Strategy Pattern)
# ---------------------------------------------------------------------------
# Set GENERATOR_STRATEGY in your .env file:
#   mock  — offline, no API key required (default)
#   suno  — live Suno API (requires SUNO_API_KEY)
GENERATOR_STRATEGY = os.getenv("GENERATOR_STRATEGY", "mock")

# Suno API key — only needed when GENERATOR_STRATEGY=suno.
# Obtain yours from https://sunoapi.org/api-key
# NEVER commit the real key; keep it in .env (which is git-ignored).
SUNO_API_KEY = os.getenv("SUNO_API_KEY", "")

# Public URL Suno will POST the completed result to.
# In production: https://yourserver.com/suno/callback/
# In local dev: leave blank — Suno will try to call the fallback URL
# (generation still works because the frontend polls /generation-status/).
SUNO_CALLBACK_URL = os.getenv("SUNO_CALLBACK_URL", "")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Required by django-allauth socialaccount
    'django.contrib.sites',
    # django-allauth — authentication & Google OAuth (FR-1.1, FR-1.2)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.headless',
    # Cithara domain app
    'music',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Required by allauth 0.56+ (must follow AuthenticationMiddleware)
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------------------------------------------------------
# Password hashing — Argon2 first (NFR: Security Requirements)
# Argon2 is the winner of the Password Hashing Competition; memory-hard.
# Falls back to PBKDF2 for existing hashes during migration period.
# ---------------------------------------------------------------------------
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# ---------------------------------------------------------------------------
# Session management (FR-1.5, NFR: Session Timeout Policy)
# Hard 30-minute timeout; sliding window resets on every authenticated request.
# ---------------------------------------------------------------------------
SESSION_COOKIE_AGE = 1800              # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True      # sliding window — resets timer on activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # also expire when browser is closed
SESSION_COOKIE_HTTPONLY = True         # JS cannot access session cookie

# ---------------------------------------------------------------------------
# Security headers (NFR: Data Encryption, Access Control)
# ---------------------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True   # prevent MIME-type sniffing
X_FRAME_OPTIONS = 'DENY'             # block clickjacking (FR-5.3, private songs)
# CSRF_COOKIE_HTTPONLY is intentionally left False (Django default).
# The JS frontend reads csrftoken from the cookie to send with AJAX requests.
# Note: SECURE_SSL_REDIRECT = True and HSTS should be enabled in production.
# Keep False here so local development works over plain HTTP.

# ---------------------------------------------------------------------------
# Authentication backends — Django ModelBackend + allauth OAuth backend
# ---------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ---------------------------------------------------------------------------
# django.contrib.sites — required by allauth socialaccount
# ---------------------------------------------------------------------------
SITE_ID = 1

# ---------------------------------------------------------------------------
# Login URL — where @login_required redirects unauthenticated requests
# ---------------------------------------------------------------------------
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# ---------------------------------------------------------------------------
# allauth configuration (headless/API mode — no HTML templates)
# ---------------------------------------------------------------------------
HEADLESS_ONLY = True                    # disable template-based auth views

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'    # skip email confirmation in dev
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' # use 'https' in production

# ---------------------------------------------------------------------------
# Google OAuth 2.0 — provider configuration (FR-1.1, FR-1.2)
# Credentials are injected from the environment (.env file).
# NEVER commit real client_id / secret to source control.
# ---------------------------------------------------------------------------
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded audio)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'music.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
